### ISSUE TITLE
Add routing to dashboard components

### ISSUE THREAD

**Issue by yash22arora** [Servatom/notefy#36]
for eg: the route for settings page should be /dashboard/settings

**Comment by Samikmalhotra** [comment]
hey i would like to work on this xd

**Comment by yash22arora** [comment]
Currently, the components are rendered dynamically based on the tab selected in the nav bar (Settings, dashboard, etc). but the route for all the pages is same i.e /dashboard. Try to add separate routes for the various components so that the page stays even on reloading. ;)
