### ISSUE TITLE
Add email confirmation

### ISSUE THREAD

**Issue by rdotjain** [Servatom/notefy#45]
Once a user registers, an email should be sent to confirm the account. If it is confirmed, only then should the user be able to log in.

**Comment by vishnu-sagubandi** [comment]
Can I work on this?? Please do assign me

**Comment by raghavTinker** [comment]
go ahead!

**Comment by chaithanyaMarripati** [comment]
how do you plan to do this @raghavTinker, send email via sendgrid with rand token and get it back via link embedded in email ??

**Comment by raghavTinker** [comment]
We will be using gmail smtp backend server to send emails in production. For development use django.console.backend

**Comment by rdotjain** [comment]
Refer to [https://arifulislam-ron.medium.com/email-verification-in-django-and-react-141dd7caf017](url)

**Comment by vishnu-sagubandi** [comment]
Added Email confirmation and created a pull request.
![Screenshot 2021-10-04 193021](https://user-images.githubusercontent.com/64656396/135865836-f9e483ac-b289-4caa-a82a-a80082418b0e.png)
Email Screenshot
![Screenshot 2021-10-04 193145](https://user-images.githubusercontent.com/64656396/135865870-a8bc6f70-b6c0-4c15-9197-3c68f1e9bb00.png)
![Screenshot 2021-10-04 193231](https://user-images.githubusercontent.com/64656396/135865917-5012212e-a1cf-417c-b533-9f1c8337c4d1.png)
![Screenshot 2021-10-04 193315](https://user-images.githubusercontent.com/64656396/135865952-b0da9018-9ef6-45f5-a376-50926e29882a.png)

**Comment by rdotjain** [comment]
Resolved in #103
