### ISSUE TITLE
Make the dashboard responsive

### ISSUE THREAD

**Issue by mannadamay12** [Servatom/notefy#47]

**Comment by itsomkathe** [comment]
Hey, I can implement it. Can you assign me?

**Comment by rdotjain** [comment]
Sure, go ahead.

**Comment by itsomkathe** [comment]
![dashboard](https://user-images.githubusercontent.com/34516916/135750247-48cc96db-f397-4126-9fc4-85c6ea66a745.PNG)
![side-bar](https://user-images.githubusercontent.com/34516916/135750248-7ae98c87-3787-495e-a3b7-afc7de462196.PNG)

Take a look at this please.
