### ISSUE TITLE
Make landing page responsive for smaller screens

### ISSUE THREAD

**Issue by yash22arora** [Servatom/notefy#48]
The current content of the landing page overflows off the screen. Fix the top area and fix the login/signup component for smaller screens.

**Comment by Amiyanshu-web** [comment]
can i work on this issue

**Comment by yash22arora** [comment]
sure!

**Comment by MuhammadTanveer94** [comment]
@yash22arora  could you please assign me this?

**Comment by MuhammadTanveer94** [comment]
@yash22arora please review https://github.com/Servatom/notefy/pull/49 PR.

**Comment by MuhammadTanveer94** [comment]
![image](https://user-images.githubusercontent.com/43910948/135696224-1fc10c1b-4e9b-427d-a357-23c84c7c8f73.png)

![image](https://user-images.githubusercontent.com/43910948/135696251-49fe6003-3890-4ed8-8764-d14a878b663e.png)

![image](https://user-images.githubusercontent.com/43910948/135696284-5162cb1e-a8a6-4ac3-933a-79971389a7f2.png)

![image](https://user-images.githubusercontent.com/43910948/135696312-e0e8d77e-dcb8-4133-838d-91e5a73fb321.png)

**Comment by yash22arora** [comment]
Can you make the title "notefy" larger and the tag line "crafted by servatom" smaller? And also please confirm that the changes are not disturbing any CSS for the larger screens? And I hope the white borders in these images are not the part of the web page.

**Comment by MuhammadTanveer94** [comment]
> Can you make the title "notefy" larger and the tag line "crafted by servatom" smaller? And also please confirm that the changes are not disturbing any CSS for the larger screens? And I hope the white borders in these images are not the part of the web page.

yes i will change the font size of title as well as tagline. It will not effect on larger screens.

**Comment by MuhammadTanveer94** [comment]
> Can you make the title "notefy" larger and the tag line "crafted by servatom" smaller? And also please confirm that the changes are not disturbing any CSS for the larger screens? And I hope the white borders in these images are not the part of the web page.

![image](https://user-images.githubusercontent.com/43910948/135716420-36245396-d39a-41a8-b407-79bf2eb5f8f6.png)

i have increase font-size of title(Notefy) and decrease font-size of tag line.

**Comment by Amiyanshu-web** [comment]
hey @yash22arora can you please once go through my PR #51 .

**Comment by yash22arora** [comment]
Hey @Amiyanshu-web , thanks for your contribution! Unfortunately, this issue has been resolved. But we would like you to contribute in our projects. You can work on some other issue or even create your own issue and we'll review it if its worth it. Thanks!
